### ISSUE TITLE
Beim Hinzufügen von Artikeln: Fehlernummer: -2147012891 Die URL ist ungültig

### ISSUE THREAD

**Issue by nesges** [JARVIS-7/BOM#1]
Egal ob durch Eintragen einer Artikelnummer in der Liste oder durch "Beobachtete Artikel einlesen" tritt folgender Fehler auf:

![JARVIS-7_2020-01-02_16-36-21](https://user-images.githubusercontent.com/1583898/71675428-07e81180-2d7e-11ea-8d08-d9ea264a7e6e.png)

Kontext: Nach Deinstallation einer alten BOM Version und Neuinstallation (kein Update) mit dem aktuellen Installer treten beim Start folgende Fehler auf:

![Biet-O-Matic_2020-01-02_16-37-23](https://user-images.githubusercontent.com/1583898/71675503-2e0db180-2d7e-11ea-80d2-19fd77645f59.png)
![image](https://user-images.githubusercontent.com/1583898/71675524-3534bf80-2d7e-11ea-9b89-349d6201f68e.png)
![image](https://user-images.githubusercontent.com/1583898/71675541-4087eb00-2d7e-11ea-92eb-c0109b873c26.png)

Die ServerStrings_ebay.de.ini ist die mit der Installation angelegte, unveränderte Version vom 27.12.2019 10:35.

Versionen:

![Biet-O-Matic_2020-01-02_16-41-53](https://user-images.githubusercontent.com/1583898/71675759-cc9a1280-2d7e-11ea-8915-bdd6d1139ae5.png)

**Comment by JARVIS-7** [comment]
Das aktuelle Installationspaket enthält Serverstrings in der Version 1.0.47.
Ich würde einfach das Installationsverzeichnis löschen und neu installieren, dann sollten die aktuellen Dateien in jedem Fall vorhanden sein und das Problem nicht auftreten.

**Comment by nesges** [comment]
Wie geschrieben: Die ServerStrings_ebay.de.ini ist die mit der Installation angelegte, unveränderte Version vom 27.12.2019 10:35.

![image](https://user-images.githubusercontent.com/1583898/71677042-015b9900-2d82-11ea-892f-69c186afb251.png)

Auszüge aus der Datei:

```; Versioninfo BOM
[BOM]
Version=2.14.16

; Versioninfo Keyfile
[Keyfile]
Version=1.0.144
```

...

```; read watchlist
[Watchlist]
ansWatchlist="[NUL]"
cmdWatchlist="MyEbayBeta&CurrentPage=MyeBayNextAllBuying&SubmitAction.ItemsPerPageSave=x&CustomizedContainer=240&ItemsPerPage=200&View=MYEBAY_NEXT_CONTAINER_CUSTOMIZE&ssPageName=STRK:MEWAX:COUNT:200&View=WatchingNext"
cmdWatchlist2="MyEbayBeta&CurrentPage=MyeBayNextAllBuying&SubmitAction.ChangeFilter=x&FormatFilter=AllFormat&StoreCatFilter=0&NewFilter=Active&Column=EndTime&ssPageName=STRK:MEWAX:FLTR:Active&View=WatchingNext"
cmdBidList="MyEbayBeta&CurrentPage=MyeBayNextAllBuying&SubmitAction.ItemsPerPageSave=x&CustomizedContainer=240&ItemsPerPage=200&View=MYEBAY_NEXT_CONTAINER_CUSTOMIZE&ssPageName=STRK:MEWAX:COUNT:200&View=WatchingNext"
ansBidStart="id="ItemDisplayContainer_BiddingNext""
ansBidEnd="</form>"
ansBidItemStart1="name="LineID""
ansBidItemStart2="/itm/"
ansBidItemPreEnd1="[NUL]"
ansBidItemPreEnd2="[NUL]"
ansBidItemEnd1="ssPageName"
ansBidItemEnd2="?"
ansBidItemEnded="[N/A]"
ansWatchStart="id="ItemDisplayContainer_WatchingNext""
ansWatchEnd="</form>"
ansWatchItemStart1="name="LineID""
ansWatchItemStart2="/itm/"
ansWatchItemPreEnd1="[NUL]"
ansWatchItemPreEnd2="[NUL]"
ansWatchItemEnd1="ssPageName"
ansWatchItemEnd2="?"
ansWatchItemEnded="[N/A]"
ansNoteStart="name="LineID""
ansNoteEnd="type="checkbox""
ansNoteTextStart="class="my_itl-nnt">"
ansNoteTextEnd="<"
ansNoteLineIDStart="value=""
ansNoteLineIDEnd="""
```

Installer bezogen von https://ssl.schnapper.de/BOM/Biet-O-Matic_install.exe, grade nochmal neu herunter geladen; keine Änderung

![image](https://user-images.githubusercontent.com/1583898/71677414-1258da00-2d83-11ea-97e5-e05c02dfced8.png)

**Comment by JARVIS-7** [comment]
Der Installer überschreibt die INI-Files nicht wenn sie jünger sind, als die im Paket enthaltenen. Eine wirkliche Versionierung findet nicht statt.
Eigentlich sollte das eine eher gute Sache sein, um individuelle Änderungen zu schützen. In diesem speziellen Fall scheint es aber eher zu schaden...
Wie gesagt: Einfach das komplette Installationsverzeichnis löschen, oder nur die INI-Dateien. Dann sollte der Installer die aktuellen Fassungen kopieren.

**Comment by nesges** [comment]
Das tue ich bereits. Ich deinstalliere BOM. Dabei wird das Verzeichnis gelöscht. Erst dann installiere ich neu.

**Comment by JARVIS-7** [comment]
Das Dateidatum der INI stimmt mit dem aus dem Installationspaket überein: 27.12.2019 10:35
Aber der gepostete Inhalt ist asbach uralt.
Aktuell ist
```
; Versioninfo BOM
[BOM]
Version=2.14.26

; Versioninfo Keyfile
[Keyfile]
Version=1.0.147


; global server settings
[Server]
; just the name :-)
AuctionHome="eBay.de"
; site URL
Webpage="www.ebay.de"
; scriptserver 1: watchl

```
Möglicherweise benötigt Windows einen Neustart, anders kann ich mir das merkwürdige Geschehen nicht erklären.

**Comment by nesges** [comment]
Ich habe die Festplatte nach ServerStrings_ebay.de.ini durchsucht und ein Kopie gefunden. Offenbar liest das Programm nicht die aus dem Installationsverzeichnis sondern mir Priorität die veraltete Kopie aus C:\Users\thomas\AppData\Local\VirtualStore\Program Files (x86)\Biet-O-Matic

![image](https://user-images.githubusercontent.com/1583898/71725326-bf8b2b00-2e33-11ea-8015-7bb61d0c711f.png)

Nachdem ich sie gelöscht habe, funktioniert BOM wieder wie gewohnt.

**Comment by JARVIS-7** [comment]
>  Offenbar liest das Programm nicht die aus dem Installationsverzeichnis 

Doch, es wird nur aus dem Anwendungsverzeichnis gelesen. Aber es ist möglich, dass Windows den App-Pfad umbiegt, wenn etwas in dem Virtual Store vorhanden ist.
Auf jeden Fall werde ich das Deinstallationsprogramm auf die Entfernung solcher Altlasten erweitern.

Schönen Dank für den Hinweis und die Geduld.
