### ISSUE TITLE
ansLinkStart nicht mehr aktuell? Such-URLs können nicht mehr eingelesen werden

### ISSUE THREAD

**Issue by kongomongo** [JARVIS-7/BOM#2]
**Beschreibe den Fehler**
Ein Such-link wie https://www.ebay.de/sch/i.html?_nkw=bubble+gum konnte früher in die "neuer Artikel" Maske gepastet werden und es wurden alle Artikel der Suchseite hinzugefügt. Dies geht nicht mehr in der 2.15.13

**Wann oder Wie tritt der Fehler auf**Wie kann man der Fehler auslösen, nach welchen Aktionen tritt er auf?
s.o.

**Umgebung**
win10

**In welchen Versionen wird BOM verwendet?**
Diese Informationen befinden sich auf dem Formular "Über..." im Menü Hilfe
 - Biet-O-Matic Version: 2.15.13
 - JARVIS-7 Version 0.9.33
 - Keyfile Version: 1.0.148

** Mögicher Fix: **
`ansLinkStart=""http://"
`
ändern in:
`ansLinkStart=""https://"
`
Ich bin mir nicht sicher ob das Absicht ist oder einfach übersehen wurde, aber alle Auktions-Links beginnen jetzt mit https...

**Comment by JARVIS-7** [comment]
Möglichweise leitet eBay nicht mehr alle URLs automatisch weiter.
In der nächten BOM-Version ist es geändert und funktioniert wieder.
